# Replace values for `CORRECT_EMAIL` and `CORRECT_PASSWORD` with a valid user's
# email and password.
CORRECT_EMAIL: 'danjohnson@gmail.com'
CORRECT_PASSWORD: 'realpassword'
FAKE_EMAIL: 'jsmith@fake.com'
FAKE_PASSWORD: 'password'
TEST: 'test_string'
